# version: '3'

# services:
#   frontend:
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile
#     volumes:
#       - ./frontend:/app
#       - /app/node_modules
#     ports:
#       - "5173:5173"
#     depends_on:
#       - backend
#     restart: always

#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     volumes:
#       - ./backend:/app
#       - /app/node_modules
#     expose:
#       - "3000"
#     depends_on:
#       - mongo
#     restart: always

#   mongo:
#     image: mongo:latest
#     expose:
#       - "27017"
#     volumes:
#       - ./data:/data/db
#     restart: always

version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_app
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    restart: always


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongodb_data:
